#UC1
create database payroll_service;
use payroll_service;
select database();

#UC2
CREATE TABLE EMPLOYEE_PAYROLL
(
ID INT unsigned NOT NULL AUTO_INCREMENT,
NAME VARCHAR(150) NOT NULL,
SALARY  DOUBLE NOT NULL,
START DATE NOT NULL,
PRIMARY KEY (ID)
);
DESCRIBE EMPLOYEE_PAYROLL;

#UC3
INSERT INTO EMPLOYEE_PAYROLL  (NAME,SALARY,START) VALUES
('Bill',10000.00,'2018-01-03'),
('Terisa',20000.00,'2019-11-13'),
('Charlie',30000.00,'2020-05-21');

#UC4
SELECT * FROM EMPLOYEE_PAYROLL;

#UC5
SELECT SALARY FROM EMPLOYEE_PAYROLL
WHERE NAME='Bill';

SELECT * FROM EMPLOYEE_PAYROLL WHERE START BETWEEN CAST('2018-01-01' AS DATE) AND DATE(NOW());

#UC6
ALTER TABLE EMPLOYEE_PAYROLL ADD GENDER CHAR(1) AFTER NAME;

UPDATE EMPLOYEE_PAYROLL SET GENDER='F' WHERE NAME='Terisa';

UPDATE EMPLOYEE_PAYROLL SET GENDER='M' WHERE NAME IN ('Bill','Charlie');

SELECT * FROM EMPLOYEE_PAYROLL;

#UC7
SELECT AVG(SALARY) FROM EMPLOYEE_PAYROLL WHERE GENDER='M' GROUP BY GENDER;
SELECT GENDER , AVG(SALARY) FROM EMPLOYEE_PAYROLL  GROUP BY GENDER;

#UC8
ALTER TABLE EMPLOYEE_PAYROLL ADD COLUMN PHONE_NUMBER VARCHAR(100) AFTER NAME;
ALTER TABLE EMPLOYEE_PAYROLL ADD COLUMN ADDRESS VARCHAR(100) AFTER PHONE_NUMBER;
ALTER TABLE EMPLOYEE_PAYROLL ADD COLUMN DEPARTMENT VARCHAR(150) NOT NULL AFTER ADDRESS;
ALTER TABLE EMPLOYEE_PAYROLL ALTER  ADDRESS SET DEFAULT 'TBO';

#UC9
ALTER TABLE EMPLOYEE_PAYROLL RENAME COLUMN SALARY TO BASIC_PAY;
ALTER TABLE EMPLOYEE_PAYROLL ADD DEDUCTION DOUBLE NOT NULL AFTER BASIC_PAY;
ALTER TABLE EMPLOYEE_PAYROLL ADD TAXABLE_PAY DOUBLE NOT NULL AFTER DEDUCTION;
ALTER TABLE EMPLOYEE_PAYROLL ADD TAX DOUBLE NOT NULL AFTER TAXABLE_PAY;
ALTER TABLE EMPLOYEE_PAYROLL ADD NET_PAY DOUBLE NOT NULL AFTER TAX;
DESCRIBE EMPLOYEE_PAYROLL;

#UC10












